### ISSUE TITLE
Lock makes category widget fail

### ISSUE THREAD

**Issue by saleiva** [CartoDB/deep-insights.js#358]
Like in this map 
https://team.cartodb.com/u/saleiva/editor/4078b5e8-0bb0-11e6-b616-0e98b61680bf/embed

If you select a neighborhood and click on lock, the widget reports an error.

**Comment by nobuti** [comment]
After digging a bit with the help of @alonsogarciapablo and @rochoa, we found out that the issue belongs to the maps api. The reason is the sql is malformed based on the parameters of the request. A new issue will be open there with further explanation. 
cc @saleiva

**Comment by rochoa** [comment]
After digging even further I noticed something really weird 😈 .

So the editor is using:
1. A layer
1. Some dataviews
1. An analysis.

Layer and dataviews point to the analysis id.

However the named map (used in the embed) has:
1. A layer *with widgets* instead of independent dataviews.
1. An analysis.

Only the layer is pointing to the analysis.

That is pretty much OK but when filters are always being applied as dataviews, but in the named maps there are no dataviews but widgets. So when filters are applied it sends something like `{"dataviews":{"04074555-d70e-489e-a040-00d61a04944c":{"accept":["South of Market"]}}}`. And that in combination with a bug in the original aggregation widget SQL we fail to `group by`.

I'm gonna create an issue in windshaft-cartodb so we unify widgets/dataviews at API/backend level so this kind of combinations can work. I have to confirm with @alonsogarciapablo that won't affect the way deep-insights.js'/cartodb.js' widgets retrieve information from them as far as URLs returned in metadata keep working.

cc @juanignaciosl @xavijam

**Comment by nobuti** [comment]
is this still a thing?

**Comment by rochoa** [comment]
I would say we can close it.
