### ISSUE TITLE
drop this repo and integrate into cartodb.js

### ISSUE THREAD

**Issue by javisantana** [CartoDB/deep-insights.js#436]
I'm not sure how valuable is to have several components in several repos when we likely are not going to use cartodb.js standalone.

discuss

cc @CartoDB/frontend @rochoa @alonsogarciapablo

**Comment by viddo** [comment]
fine by me

**Comment by alonsogarciapablo** [comment]
Hey! IMO we should prioritise this. Right now is a bit painful having to deal with two separate libraries (two deps for BUILDER and two different APIs) and, as @javisantana mentioned in the description, it's not adding any value since nobody is just rendering "maps". We could categorise this as tech debt.

cc: @rochoa @jorgesancha

**Comment by jorgesancha** [comment]
Removing from TODO because it seems the decision depends on Carto.js dev plan

**Comment by javisantana** [comment]
I'd close this since it'll probably a different thing
