### ISSUE TITLE
Time series widget shows a date with a number column

### ISSUE THREAD

**Issue by xavijam** [CartoDB/deep-insights.js#441]
![screen shot 2016-08-10 at 11 16 49](https://cloud.githubusercontent.com/assets/132146/17548381/f4dd4f9c-5eeb-11e6-9664-d049347d062c.png)

**Comment by viddo** [comment]
@xavijam any STR on how to reproduce the scenario?

**Comment by xavijam** [comment]
Not really, I've just tried it in the builder (private side).

**Comment by viddo** [comment]
I think there's two things needed:
- Pass `column_type: 'number'` if it's not a date, by default it assumes the column to be a `date` if none is given, this is used by the underlying dataview to get the data correctly/as expected
- Implement (currently missing) views for discrete range instead of dates (can decide which based on the column type).

**Comment by xavijam** [comment]
Already done!
