### ISSUE TITLE
Autostyling working in Builder but not on embed

### ISSUE THREAD

**Issue by makella** [CartoDB/deep-insights.js#457]
@rochoa 

I made a map:
https://team.carto.com/u/mamataakella/builder/92096530-ccf0-4a97-8a29-7b0c2fe89061/embed

If you click on any of the Autostyling options in the widgets, you will notice unexpected behavior. Some polygons are getting colored with the autostyle colors and others are not.

![screen shot 2016-10-05 at 9 53 46 am](https://cloud.githubusercontent.com/assets/1566273/19120862/a481713c-8ae1-11e6-9ac3-af377228ab6b.png)

Now, when I do the Autostyling inside of Builder, it works as expected:

![screen shot 2016-10-05 at 9 54 55 am](https://cloud.githubusercontent.com/assets/1566273/19120894/cb8d071e-8ae1-11e6-9c9a-74aa0a7b38e1.png)

So, I'm not sure what is happening between the Builder map and the embed.

Any help is appreciated!

Table:
https://team.carto.com/u/mamataakella/dataset/final_election_subquery_copy

**Comment by makella** [comment]
.carto incase it helps:

[Democratic Primary Results (Clinton v Sanders) (on 2016-10-05 at 16.25.10).carto.zip](https://github.com/CartoDB/deep-insights.js/files/511731/Democratic.Primary.Results.Clinton.v.Sanders.on.2016-10-05.at.16.25.10.carto.zip)

**Comment by javisantana** [comment]
Ok, the problem is actually a big and hard to explain one.

So this map has a layer with a custom style (which is actually a nice usage of turbocarto):

```
#layer {

  line-width: 0;
  line-color: #FFF;
  line-opacity: 0.5;
  polygon-gamma: 0.4;
  polygon-opacity: 0.9;
  polygon-fill: #d3d3d3;
  [d_winner ='Sanders']{
    polygon-fill: ramp([d_margin_pc], cartocolor(Peach), quantiles(4));
  }

  [d_winner ='Clinton']{
    polygon-fill: ramp([d_margin_pc], cartocolor(Teal), quantiles(4));
  }
}
```

When the editor applies autostyling (and works in the expected way) it replaces `polygon-fill` with the autostyler one in this line: https://github.com/CartoDB/deep-insights.js/blob/master/src/widgets/auto-style/category.js#L9

The way autostyle works in hacky, since we didn't have time to do it properly we did a hack with regexp to replace the polygon colors just replacing that attribute.

The problem in the embed (where it does not work properly) is the replacement is not done over the turbocartocss, is done in the compiled cartocss (turbocartocss is transformed to cartocss by the maps api) so the replacement does not work.

The proposed solution is to do this in 2 passes:

1) remove all the polygon fills in the style
2) add polygon-fill with the autostyle generated one

Anyway, the right way would be to:

1) parse cartocss
2) with parsed structure remove all polygon fills and add the polygon-fill for the whole layer
3) generate cartocss again with the modified structure
