### ISSUE TITLE
Improve widgets error state for supporting several error types

### ISSUE THREAD

**Issue by xavijam** [CartoDB/deep-insights.js#574]
When there is an error in the Dataviews request, widgets can be rendered. We display an error saying "There has been an error" (or something like that), and a refresh button (is it useful?).

From now on we should be more concrete about the problem. We should catalog those by:

- Data error: any dataview request returned an error and we should display it.
- Limits error: the user has reached its platform limits, dataview request will fail but with a specific error code or message, so we should decide if the error message should change or not (**let's not forget this will be public in the embed page**).

## Design

![d60763a6-3a63-11e7-8d97-120b649726e3](https://user-images.githubusercontent.com/132146/29208324-e65d7eb0-7e89-11e7-8937-a04a80a645cf.png)

*Related ticket: https://github.com/CartoDB/cartodb-platform/issues/3279

**Comment by rubenmoya** [comment]
Hi! I've seen in this issue https://github.com/CartoDB/cartodb/issues/12751 the widget error text has changed, right now, for the limits engine is sending this error:

```
{
  type: 'limit',
  message: 'You are over platform\'s limits. Please contact us to know more details',
  subtype: 'datasource'
}
```

Should we separate both errors, timeout (poor connectivity, error with the server) and limits (database/tiler timeout), or keep the same error for both of them?

Also, I've realised, since we're going to have more feedback about the errors, is it still necessary the design with only one button or can we use the last one in this design for that case?

![30542755-df01e812-9c80-11e7-9e45-12eb7727afe2](https://user-images.githubusercontent.com/16247628/30542755-df01e812-9c80-11e7-9e45-12eb7727afe2.png)

cc @CartoDB/design

**Comment by arianaescobar** [comment]
IMO, we should separate them. We might want to improve the copy for that limits error and prepare the visual. 

Regarding your last question: if we have specific information about the error (like limits or poor connectivity) I would show the full message to properly explain it. But if we don't, I recommend avoiding the repetition of elements. Right now, in the following case, the buttons already feel super repetitive, if we also add a generic message and repeat it all over, it will be too much. 

![30153886-6e0539c8-93b8-11e7-8952-24cae556e718](https://user-images.githubusercontent.com/16247628/30699445-11377908-9ee5-11e7-976a-1c3d169ddc13.png)

**Comment by noguerol** [comment]
I totally agree, @CartoDB/design . New ticket for that, please!

**Comment by rubenmoya** [comment]
I think we already have both tickets, this one for the errors and the other one for the button styles, right?

Btw, right now when there is no data, the widget shows emtpy:

![screen shot 2017-09-22 at 11 46 10](https://user-images.githubusercontent.com/905225/30738893-d0b4b916-9f8b-11e7-9025-7a501ca259cf.png)

Should I replace that with the "No data available" design?

**Comment by arianaescobar** [comment]
Yes and yes @rubenmoya

**Comment by rjimenezda** [comment]
On production 🚢

**Comment by xavijam** [comment]
:dancer:
